// Generates a MySQL script that loads transactions and alerts into the schema in sql/schema.sql.
#include <cstdio>
#include <fstream>
#include <set>
#include "io.hpp"
#include "timeutil.hpp"

namespace {
std::string q(const std::string& s) {                         // quote + escape for a SQL string literal
    std::string o = "'";
    for (char c : s) { if (c == '\'' || c == '\\') o += '\\'; o += c; }
    return o + "'";
}
std::string num(double v, int d) { char b[40]; std::snprintf(b, sizeof b, "%.*f", d, v); return b; }
std::string reasons(const std::vector<std::string>& r) { std::string s; for (size_t i = 0; i < r.size(); ++i) s += (i ? "; " : "") + r[i]; return s; }
}  // namespace

bool writeSqlScript(const std::string& path, const std::vector<Transaction>& tx, const std::vector<Signals>& sig, double alertThreshold) {
    std::ofstream f(path);
    if (!f) return false;
    f << "-- Generated by Banking Anomaly Detector. Run sql/schema.sql first.\nUSE banking_anomaly;\nSTART TRANSACTION;\n";

    std::set<std::string> accounts;
    for (const auto& t : tx) { accounts.insert(t.sender); accounts.insert(t.receiver); }
    f << "INSERT IGNORE INTO accounts (account_id) VALUES\n";
    for (auto it = accounts.begin(); it != accounts.end();) { f << "  (" << q(*it) << ")"; f << (++it != accounts.end() ? ",\n" : ";\n"); }

    const size_t batch = 500;
    for (size_t b = 0; b < tx.size(); b += batch) {
        f << "INSERT INTO transactions (tx_id, account_id, receiver_id, tx_time, amount, merchant, is_injected, anomaly_type) VALUES\n";
        for (size_t i = b; i < tx.size() && i < b + batch; ++i) {
            const auto& t = tx[i];
            f << "  (" << q(t.id) << ", " << q(t.sender) << ", " << q(t.receiver) << ", " << q(formatTime(t.ts)) << ", "
              << num(t.amount, 2) << ", " << q(t.merchant) << ", " << (t.injected ? 1 : 0) << ", " << q(t.anomalyType) << ")"
              << ((i + 1 == tx.size() || i + 1 == b + batch) ? ";\n" : ",\n");
        }
    }
    bool first = true; size_t inBatch = 0;
    for (size_t i = 0; i < tx.size(); ++i) {
        if (sig[i].risk < alertThreshold) continue;
        if (first || inBatch == batch) {
            if (!first) f << ";\n";
            f << "INSERT INTO alerts (tx_id, rule_score, graph_score, ml_score, risk_score, risk_level, reasons) VALUES\n";
            inBatch = 0; first = false;
        } else f << ",\n";
        const auto& s = sig[i];
        f << "  (" << q(tx[i].id) << ", " << num(s.ruleScore(), 3) << ", " << num(s.graphScore(), 3) << ", " << num(s.ml, 3) << ", "
          << num(s.risk, 3) << ", " << q(s.level) << ", " << q(reasons(s.reasons)) << ")";
        ++inBatch;
    }
    if (!first) f << ";\n";
    f << "COMMIT;\n";
    return static_cast<bool>(f);
}
